### ISSUE TITLE
`?` in `main` #1937

### ISSUE THREAD

**Issue by carols10cents** [request-for-explanation/podcast#1]
https://github.com/rust-lang/rfcs/pull/1937

**Comment by carols10cents** [comment]
I'd like to propose this as Monday's episode

**Comment by Manishearth** [comment]
Next episode is #20 since that's a big RFC and we're able to get aturon on.

This can be the one after.

(Might want to roll this in with a different RFC, unsure if we can fill 20 minutes with this. though talking about the history of `?` would be interesting)

**Comment by Manishearth** [comment]
Should this be next? Or should we choose a different one (or do one of the meta podcasts)

**Comment by carols10cents** [comment]
shrug! wdyt?

**Comment by Manishearth** [comment]
I'm _shrug_ too 😄

**Comment by Manishearth** [comment]
RFE 5
