### ISSUE TITLE
Navigation link at the top of the page

### ISSUE THREAD

**Issue by sunjay** [request-for-explanation/podcast#17]
Hi!
Thanks for making this podcast!

Could you add some navigation links to the top of the page? I see that you have a back to home link on the bottom, but users (like me) commonly look for something at the top of the page to take them back to the index/home page of the site. (Examples: the GitHub logo on the top left, Facebook logo on Facebook.com, etc.)

This is especially useful on mobile where scrolling all the way to the bottom of the transcript just to go home is fairly counterintuitive. 

A link that says something like "Episode List" or "Home" would be awesome.

Really excited for further episodes!

P.S. this is unrelated to this issue, but if you were to post this on [Google Play Music podcasts](https://play.google.com/music/podcasts/publish), I would definitely listen to it there. Would make it super convenient!

**Comment by Gankra** [comment]
Whoever wants to do this: you just need to edit src/before.html and regenerate the only episode (per README)

**Comment by Gankra** [comment]
Clarification: I can do the regeneration if this too burdensome :)

**Comment by sunjay** [comment]
@Gankro [Since you made it so easy](https://github.com/request-for-explanation/podcast/pull/18) :smile:
