### ISSUE TITLE
Generic associated types (associated type constructors) #1598

### ISSUE THREAD

**Issue by carols10cents** [request-for-explanation/podcast#2]
https://github.com/rust-lang/rfcs/pull/1598

@sgrif I think this is the one you meant when you suggested ATCs?

**Comment by sgrif** [comment]
Yes.

**Comment by sgrif** [comment]
If you ever did want to do guest episodes and want someone w/ opinions on this who isn't the RFC author, I'd love to talk about this one -- boats would probably be better though

**Comment by carols10cents** [comment]
def want people interested in discussing things on as guests, whether or not they're the author :)

**Comment by Manishearth** [comment]
@withoutboats @sgrif anyone up for doing this the coming Monday? Carol isn't free so I'll probably host.

**Comment by sgrif** [comment]
Sure, shoot me a calendar invite.

**Comment by Manishearth** [comment]
This happened as RFE 4
