### ISSUE TITLE
Episode idea: Background on the RFC process

### ISSUE THREAD

**Issue by onelson** [request-for-explanation/podcast#21]
I've been writing rust for a few months now, and something I've had trouble sorting out from following the RFCs is the overall lifecycle. I've been following discussions on many RFCs, but am yet to see anything go from RFC to usable in the toolchain. I'm sure it'll become clear in time, but being new to the community, I'd love some insight on this from folks involved in the process.

I was hoping you'd like to discuss the RFC process, and what happens to an RFC once it's accepted. How does the work get done? What is the process for promotion through nightly, beta, stable?

Perhaps this is too high level for the podcast, and that's fine, but I thought I'd pitch the idea just in case!

Cheers,
Owen

**Comment by onelson** [comment]
So, here I am reporting an issue that is largely duplicate of #8 :(
Maybe there's something here to help inform what to cover.

**Comment by Manishearth** [comment]
moved comment to #8, thanks for the feedback!
