### ISSUE TITLE
Publish to Google play music

### ISSUE THREAD

**Issue by sunjay** [request-for-explanation/podcast#27]
Would love to subscribe to this podcast on Google play music! Here's some information about publishing: https://play.google.com/music/podcasts/publish

From what I've heard it's quite easy to do. :)

**Comment by Manishearth** [comment]
Updated the RSS feed to work with this, and put it through the process. There seems to be a review step.

**Comment by sunjay** [comment]
Thank you!

**Comment by Manishearth** [comment]
https://play.google.com/music/listen#/ps/I3m3hme5dehaze2edwuijovqcfm

**Comment by sunjay** [comment]
Thanks!!

![20170711_121934](https://user-images.githubusercontent.com/530939/28078549-3b732964-6633-11e7-971f-e291da801413.png)
