### ISSUE TITLE
iTunes

### ISSUE THREAD

**Issue by carols10cents** [request-for-explanation/podcast#28]
I tried submitting our RSS feed here https://podcastsconnect.apple.com/

And got these errors that we have to fix:

- Podcast artwork must be between 1400 x 1400 and 3000 x 3000 pixels, JPG or PNG, in RGB color space, and hosted on a server that allows HTTP head requests.
- Can’t submit your feed. There is no category tag in your feed, or the category tag is empty.
- Can’t submit your feed. There is no explicit tag in your feed, or the explicit tag is empty.

**Comment by Manishearth** [comment]
Fixed up and submitted.

**Comment by Manishearth** [comment]
https://itunes.apple.com/us/podcast/request-for-explanation/id1258783754 

Won't show up just yet, but soon. It's approved.

Someone should add a badge to the homepage.
