### ISSUE TITLE
Figure out a license

### ISSUE THREAD

**Issue by Manishearth** [request-for-explanation/podcast#29]
https://wiki.creativecommons.org/wiki/Podcasting_Legal_Guide

**Comment by carols10cents** [comment]
what more than CC-BY do we need to do? https://wiki.creativecommons.org/wiki/Podcasting_Legal_Guide#Applying_A_CC_License_To_Your_Podcast.

**Comment by Manishearth** [comment]
Fine with cc by, just need agreement from the authors :smile:

Cc @gankro

**Comment by carols10cents** [comment]
but... we already did this.... https://github.com/request-for-explanation/podcast/issues/6

**Comment by Manishearth** [comment]
I'm stupid
