### ISSUE TITLE
RFC 2091: Semantic inlining

### ISSUE THREAD

**Issue by Manishearth** [request-for-explanation/podcast#31]
https://github.com/rust-lang/rfcs/pull/2091

https://github.com/kennytm/rfcs/blob/inline-semantic/text/0000-inline-semantic.md

IT HAS BULLET POINTS. NESTED BULLET POINTS. WE MUST DO THIS.

**Comment by carols10cents** [comment]
YESSSS 

Hey @kennytm, would you like to be on the Request for Explanation podcast and chat with us about your RFC 2091? If so, we typically record for about 30-45 min starting at 5:30pm ET on Mondays, but we can be flexible. Would that time work for you, and if so, which monday? If not, what are some other times that would work for you? :)

**Comment by kennytm** [comment]
@carols10cents 5:30pm EDT (UTC-4) Monday would be 5:30am HKT (UTC+8) Tuesday 😱 I'm more free on 9pm–1am for weekdays (that translates to 9am–1pm same day for EDT).

**Comment by Manishearth** [comment]
10/11AM EDT works for me.

**Comment by carols10cents** [comment]
Whoops, sorry about that, didn't know what time zone you were in!! Definitely don't get up at 5:30am for this!!!! 😆

10/11am EDT works for me most days. What day would be good for you?

**Comment by kennytm** [comment]
@carols10cents any Monday ..= Thursday is fine.

**Comment by carols10cents** [comment]
@kennytm @Manishearth how about Tues Aug 8 at 10:30am EDT? That's Tues 7:30am PDT and 10:30pm HKT if I've done my math correctly?

**Comment by Manishearth** [comment]
10:30PM Higher Kinded Types sounds good to me

**Comment by Manishearth** [comment]
Wait isn't #15 the next episode? We should get the guests for that though.

I mean, we could do one on monday and one on tuesday (I'm up for it) and perhaps publish it later.

**Comment by kennytm** [comment]
@carols10cents LGTM

**Comment by carols10cents** [comment]
cool, let's do this :) @kennytm to what email should we send a calendar invite? have you used vidyo before?

**Comment by kennytm** [comment]
@carols10cents Never used that before :). You may send to kennytm at gmail dot com.

BTW I'll update the RFC tonight to incorporate some of the feedback, hopefully it won't affect much here.

**Comment by carols10cents** [comment]
> Never used that before :)

Ok can you try downloading the vidyo desktop client from https://v.mozilla.com/download.html?lang=en ? Once you have that installed and opened, tomorrow when you open the link in the invite it should put you in the room. If any of this doesn't work, we'll fall back to something else... google hangouts? skype? We don't record video, but sometimes it's nice to be able to gesture through it.

> BTW I'll update the RFC tonight to incorporate some of the feedback, hopefully it won't affect much here.

That's totally fine! I like asking about changes RFCs have gone through, so we can talk about them if you want :)

**Comment by Manishearth** [comment]
@kennytm it's published at https://request-for-explanation.github.io/podcast/ep7-unwrapping-a-great-rfc/index.html

thanks again!
