### ISSUE TITLE
RFC 2094: 👏 M O T H E R 👏 H U G G I N G 👏 N O N 👏 L E X I C A L 👏 L I F E T I M E S 👏

### ISSUE THREAD

**Issue by Gankra** [request-for-explanation/podcast#32]
https://github.com/rust-lang/rfcs/pull/2094

**Comment by Manishearth** [comment]
tfw no longer worried about explicit content

**Comment by Gankra** [comment]
👏 clapping 👏 emoji 👏 protect 👏 you 👏 from 👏 everything 👏

**Comment by Manishearth** [comment]
lol @ the rename.

realized that this gets autolinked on the RFC, did you? :p

**Comment by Gankra** [comment]
👏 MAYBE 👏

**Comment by Manishearth** [comment]
@nikomatsakis would you like to be a guest on an RFE episode for this? Probably the monday after the next (the 14th), but we're flexible. We usually record at 2:30PDT (5:30PM EDT) but this is flexible. Typical recordings go on for less than an hour -- the intent has always been to have 20m long episodes but we usually go over that and now they're usually around 40 minutes.

**Comment by carols10cents** [comment]
I believe Niko is on vacation until the 15th; we may want to push this til after rustconf :)

**Comment by nikomatsakis** [comment]
Hi all =) I'm back now, I would indeed be happy to talk about NLL. What dates would be good?

**Comment by Manishearth** [comment]
We typically do the recording on Monday 2:30PDT (5:30PM EDT), but we can be flexible.

**Comment by Manishearth** [comment]
We've decided to do modules on monday (https://github.com/request-for-explanation/podcast/issues/37), but we can probably do NLL any other day that week at the same time, or the next monday. Let us know when you're free.

**Comment by Manishearth** [comment]
This was RFE 9 

https://github.com/request-for-explanation/podcast/commit/5960ce60db57b3fd6bcb49dbb5aa3247038c88e6
