### ISSUE TITLE
#2071 impl Trait type alias

### ISSUE THREAD

**Issue by Manishearth** [request-for-explanation/podcast#34]
https://github.com/rust-lang/rfcs/pull/2071

Might be interesting

**Comment by aturon** [comment]
Yes! Please do this one -- it's hugely important but I think people aren't grokking the implications. Also @cramertj would be a great guest :)

(Though Vidyo is pretty crashy for him...)

**Comment by cramertj** [comment]
I'd love to help out with this-- I have some nicer audio gear at my house (along with a Windows machine, which is potentially less Vidyo-averse than my Goobuntu laptop).

**Comment by Manishearth** [comment]
Ok, so we're doing #31 tomorrow, and #15 during RustConf (provided the plan to kidnap the likely-busy aturon during the conf works out).

How does next Monday the 14th, 2:30PM PDT sound? I'll send you an invite if that works (will need a Google Calendar compatible email address). We're flexible on the timings though.

http://everytimezone.com/#2017-8-14,570,cn3

**Comment by Manishearth** [comment]
Given that this is a pretty intricate RFC I would expect this episode to be around 40m long.

We try to keep it at 20 but so far most episodes hit 30+. So budget for an hour after the scheduled time.

**Comment by cramertj** [comment]
Oh, okay-- if it's during the work day (PST) then I won't have access to recording stuff, and Vidyo will be flakey on my laptop/work computer. Any chance we could do next Tuesday or Wednesday evening? If not, I'll be at RustConf, or we can try and figure out a day afterwards.

**Comment by Manishearth** [comment]
Does an hour earlier tuesday the same time work for you? (also @carols10cents / @Gankro ?)

(1:30PM PST tuesday works for me, but not 2:30PM won't work.)

**Comment by Manishearth** [comment]
3PM PST also works for me, but that might get late for the east coast folks.

**Comment by cramertj** [comment]
Yeah, I could do 1:30 next Tuesday-- I'll try and see if I can get ahold of a computer that behaves with Vidyo :)

**Comment by Manishearth** [comment]
WFM. got an email address?

**Comment by cramertj** [comment]
cramertaylorj@gmail.com or cramertj@google.com

**Comment by Manishearth** [comment]
Invite sent! There's a link in there for the vidyo room. (Room might be locked right now and may not work, let  me know if you need to test it out)

**Comment by Manishearth** [comment]
https://paper.dropbox.com/doc/RFE-8-An-existential-crisis-LahoYNGtwUQ3vJhhBoGni is where we'll sketch out the questions and such

**Comment by cramertj** [comment]
Thanks so much for having me on! @Manishearth @carols10cents @Gankro
