### ISSUE TITLE
New modules RFC

### ISSUE THREAD

**Issue by Manishearth** [request-for-explanation/podcast#37]
https://github.com/rust-lang/rfcs/pull/2126

IT HAS BEGUN

**Comment by Manishearth** [comment]
@withoutboats @aturon want to be guest(s) on this one?

We're already planned for the next three weeks (impl trait alias, what makes a great rfc, NLL (hopefully)) but sometime after that would be great. Or we could squeeze in an episode in the coming weeks if @carols10cents/@Gankro are up to it. Perhaps even during RustConf, though we're _already_ recording an episode with Aaron there.

**Comment by Manishearth** [comment]
Episode title: "Two paths diverged in a yellow wood"

**Comment by Manishearth** [comment]
Penciling in for Monday, August 28, 2:30PDT. @aturon is free then.

cc @carols10cents @Gankro @withoutboats 

lmk if anyone has scheduling issues and I can shift it around.

**Comment by Gankra** [comment]
Not interested in this one; not my bag
