### ISSUE TITLE
eRFC: Experimentally add coroutines to Rust #2033

### ISSUE THREAD

**Issue by carols10cents** [request-for-explanation/podcast#4]
https://github.com/rust-lang/rfcs/pull/2033

**Comment by carols10cents** [comment]
@alexcrichton want to be a guest on this episode? we're generally recording mondays at 5:30pm ET, would that work for you? if so, which monday? :)

**Comment by alexcrichton** [comment]
Certainly! Would next Monday work alright?

**Comment by Manishearth** [comment]
wfm.

**Comment by Manishearth** [comment]
Invite sent

**Comment by Manishearth** [comment]
RFE 6
