### ISSUE TITLE
Improve sound quality for the podcasts

### ISSUE THREAD

**Issue by toidiu** [request-for-explanation/podcast#40]
It is sometimes difficult to hear the speakers, especially on trains/subways or places with ambient noise. Somethings I would suggest:

- increase the maximum volume (people can always turn it down)
- possibly better recording equipment or making a point to speak directly into the microphone
- some post recording audio processing

Thanks for the podcast

**Comment by Manishearth** [comment]
We've basically decided not to put additional effort into audio processing.

**Comment by thevtm** [comment]
That's sad!
I really like this podcast but sometimes is hard to understand what is being said (not an English native speaker).
Post processing can be a pain but I there are some tools that simplify that process drastically.
Take at some tools specifically for recording podcast like [Cast](https://tryca.st), [RINGR](https://www.ringr.com/) and [Zencastr](https://zencastr.com/).
[How to Get Good Audio from Your Podcast Guests – TAP304](https://theaudacitytopodcast.com/how-to-get-good-audio-from-your-podcast-guests-tap304/)
Keep it up! :smile:
