### ISSUE TITLE
RFC 2126: Clarify and streamline paths and visibility (modules)

### ISSUE THREAD

**Issue by carols10cents** [request-for-explanation/podcast#41]
https://github.com/rust-lang/rfcs/pull/2126

@aturon @withoutboats @Manishearth want to do this one Monday 9/25?

**Comment by aturon** [comment]
I'm game! Note that the RFC didn't change much since the last podcast, but it'd be good to recap a few of the key points.

**Comment by carols10cents** [comment]
The fact that it doesn't require epochs and subsumed the RFC that gets rid of `extern crate` are p big changes, imo :)

**Comment by aturon** [comment]
Heh. I'm pretty sure the latter was true at the time of the last podcast. But anyway: let's do it!

**Comment by Manishearth** [comment]
@carols10cents we did a podcast for this rfc in mostly its current form a few weeks ago.

Open to another one, just letting you know.

Would be interesting to have one as a retrospective on how this RFC progressed and how the process could have been improved for this.

**Comment by carols10cents** [comment]
OH THIS WAS THE ONE I MISSED no wonder i don't remember any of this!! 

I think I was thinking of the episode we did on epochs and thinking that one was on modules, and was a while ago. NEVERMIND
