### ISSUE TITLE
eRFC 2136: Cargo build system integration

### ISSUE THREAD

**Issue by carols10cents** [request-for-explanation/podcast#42]
https://github.com/rust-lang/rfcs/pull/2136

@aturon want to be on this one? or @joshtriplett perhaps? (Hi Josh, want to be on a podcast episode explaining the build system RFC? :))

**Comment by aturon** [comment]
Happy to do it, but even happier to have @joshtriplett do it :-)

Maybe you can get @wycats on one of these!

**Comment by joshtriplett** [comment]
I'd be happy to.

**Comment by carols10cents** [comment]
@joshtriplett are you available Mon 9/25 at 5:30pm ET/2:30pm PT?

**Comment by joshtriplett** [comment]
@carols10cents I can make that work, sure.

(As another option: I'll be at RustFest Zurich, if any RFE folks might be there and want to speak in person. :) )

**Comment by carols10cents** [comment]
I won't be at rustfest, idk who will be :-/ Does today (in 3.5 hrs) still work? Is vidyo ok? (we only need audio)

**Comment by joshtriplett** [comment]
@carols10cents Today still works, at 2:30pm US/Pacific. Vidyo is OK if you have a phone number / meeting code I can use; otherwise, I could do Hangouts, phonecall, or whatever else would be convenient.

**Comment by Manishearth** [comment]
Got an email address I can use? The calendar invite will have everything

**Comment by joshtriplett** [comment]
josh@joshtriplett.org

**Comment by Manishearth** [comment]
invite sent. if you don't get it lmk and I'll send you the details directly.

**Comment by joshtriplett** [comment]
@Manishearth Received, but it didn't include a phone number / conference code.

**Comment by Manishearth** [comment]
Is there not a link from which you can use vidyo?

I can figure out the number though, hold on.

**Comment by Manishearth** [comment]
https://paper.dropbox.com/doc/RFE-11-insert-pithy-title-here-IX0KBJQPfeR5kYhKMRUML

**Comment by Manishearth** [comment]
https://request-for-explanation.github.io/podcast/ep11-cargo-culting-the-build-system/index.html
