### ISSUE TITLE
Better audio quality

### ISSUE THREAD

**Issue by dsvensson** [request-for-explanation/podcast#46]
Great pod, but the low audio quality takes some joy out of it. Check out New Rustacean for a comparison. Maybe you could get some tips from that production.

**Comment by Manishearth** [comment]
When we started this we declared that we weren't going to put effort into that, we simply don't have the time. New Rustacean does a _significant_ amount of post processing.

https://github.com/request-for-explanation/podcast/issues/40

**Comment by dsvensson** [comment]
@Manishearth ah, bad example. I wasn't at all interested in any fancy post-processing, intro tune or anything like that. Just better audio-quality so that it doesn't sound like you all speak through a phone from the early 1900s. This request has nothing to do with aesthetics, but simply being able to consume the information you're trying to convey. Right now it sound like you're recording the episodes in 11kHz. Isn't there anything you can do to effortlessly improve that situation? Considering how everyone and their dog are recording podcasts nowadays with high quality audio there surely must be better software, if that's the culprit, and good enough microphones are crazy cheap from AliExpress as well, and donations could help if that's still too much. Right now information is lost and that's a shame.

**Comment by Manishearth** [comment]
> Isn't there anything you can do to effortlessly improve that situation?

Not that I know of.

We have a convenient setup for software for this already. I've looked into this a bit; it's not easy to improve.

The only way to improve this is if folks did local recording and I stitched it together later; but this seems to involve nontrivial post processing again.

**Comment by dsvensson** [comment]
@Manishearth just started episode 1 and whatever you did there, just do it again. Sounds great. Or you're in the same room in that ep?

**Comment by Manishearth** [comment]
Yes.

**Comment by dustinmatlock** [comment]
I’m finding the only possible way to listen is with isolation equipment. Otherwise, I miss around 80% of the content. Longer, in-depth podcasts for Rust do not currently exist, so it was a shame to have this experience. Thanks for considering.
