### ISSUE TITLE
Match Ergonomics Using Default Binding Modes #2005

### ISSUE THREAD

**Issue by carols10cents** [request-for-explanation/podcast#5]
https://github.com/rust-lang/rfcs/pull/2005

Agenda:

- Intro of each person
- Explain the concept of the podcast: give misdreavus (pronounced miss-DREE-vus) credit for coming up with this idea http://logs.glob.uno/?c=mozilla%23rust-community&s=21+Dec+2016&e=21+Dec+2016#c14196

- Gankro summarize the RFC
  - How does this change things?
  - Why does this make things better?
- Talk about the previous RFC https://github.com/rust-lang/rfcs/pull/1944
- Conclude - file issues!

**Comment by Gankra** [comment]
Written summary here: https://gist.github.com/Gankro/95390640bac8418661561d0f472f9294

It's not clear to me to what extent the technical details matter at all.

**Comment by carols10cents** [comment]
Ok what time are people available, should i make a doodle poll and should we try and make a recurring time or should we schedule episode by episode? 

first proposal: 5:30pm EDT/2:30pm PDT on monday

**Comment by Gankra** [comment]
My schedule is generally incredibly flexible. That time works fine for me.

**Comment by carols10cents** [comment]
oh and i want to aim for this to take about 30 min total... it might take us longer to get our act together the first few times tho. I'm not going to edit the first few (unless someone wants to volunteer to do so); figure we should prove out that people find the content useful before we worry too much about audio quality. So if we're going for 20 min, hopefully we can get the whole "is-everyone's-sound-working" part down pretty low

**Comment by Manishearth** [comment]
Works fine for me. 

What I'd expect is that we take 10m beforehand to just plan out the general flow of the discussion, and then just ... do that for 20mish.

That time doesn't work for me on tuesdays and wednesdays though (an hour later does).


Yeah, I think that we don't need to edit it. Totally fine with dropping podcasts with low audio quality, I really only care about the content 😄

**Comment by carols10cents** [comment]
@manishearth: does that time work for you on mondays?

**Comment by Manishearth** [comment]
yep

**Comment by carols10cents** [comment]
ok you two should have an invite. made it recurring to block your calendars, we can tweak as necessary. google hangout ok or do yinz want to do vidyo or skype or something else?

**Comment by Manishearth** [comment]
Hangout is fine. Vidyo lets me use the conf rooms with decent sound recording though (Unsure what the experience is like on your end for vidyo)

**Comment by Gankra** [comment]
Also vidyo protects us from all steve klabniks

**Comment by Manishearth** [comment]
This is Important ™️

**Comment by carols10cents** [comment]
Oh no he's on windows now so he can totally do vidyo

**Comment by carols10cents** [comment]
I don't mind vidyo, and I also don't mind if you take care of the sound recording @manishearth <3

**Comment by carols10cents** [comment]
@manishearth could you add a vidyo link to the invite series? you should have permission to edit it now

**Comment by Manishearth** [comment]
done

**Comment by sgrif** [comment]
I highly recommend having everyone record their own audio if possible, even if it's just a precaution. The audio quality will be greatly improved especially for those who have a decent mic. On Mac you can record from Quicktime for free, though https://www.rogueamoeba.com/audiohijack/ is good and reasonably cheap. I can ask our producer for Linux/Windows recommendations as well.

**Comment by carols10cents** [comment]
ep 0 is done!!
